### ISSUE TITLE
Read rights per issue

### ISSUE THREAD

**Issue by wgjohnson** [burningmantech/ranger-ims-mac#44]
Feature request on behalf of the Greendot Cadre:

>As a Greendot, I'd like anything I enter into IMS to have read permission for only me (the person who opened the issue), Greendot Leads, RSLs, and OODs.

>As a Greendot lead, I'd like to edit the read permissions for any Greendot IMS issue in order to add new Greendot Rangers assigned to the issue.

The current work around is a policy from the Ops Manager that all teams will use IMS regardless of technical controls for confidentially, though I can see this being a desired feature for the RSC team (OOD's discretion, 007 notes, etc.)

**Comment by flwyd** [comment]
Other than GD Leads, RSLs, and OODs, the only groups I can think of with access to IMS are the Operators and RSCIs.

I'd be concerned about barring Operators access to any incidents since they're often doing research or appending notes on behalf of other folks.  It could also lead to an incorrect belief about the absence of data: an RSL could ask an Operator to see if there are any prior incidents at Camp Poopyface.  "Just a sound complaint on Monday" is a very different answer than "A sound complaint, plus two intense Green Dot incidents."

**Comment by wsanchez** [comment]
Yeah, the whole point of this system is that we have a centralized source of critical data accessible by our shift command team, which includes operators.  At this point, anyone with an IMS has to sign an NDA and if we don't trust them to honor it, they shouldn't have an account.

The complexity of adding access controls (to entire incidents, or just the text, or also the summary?) and then administering access (shit why can't I open this? who do I talk to to fix that? etc.) doesn't seem worthwhile.

**Comment by wgjohnson** [comment]
Understood. Will communicate that back.
